name: Build and push packages

on:
  workflow_dispatch:
    inputs:
      nr_project_nodes_release_name:
        description: 'nr-project-nodes package version'
        required: false
        default: 'nightly'
      nr_project_nodes_ref:
        description: 'nr-project-nodes package ref'
        required: false
      nr_file_nodes_release_name:
        description: 'nr-file-nodes package version'
        required: false
        default: 'nightly'
      nr_file_nodes_ref:
        description: 'nr-file-nodes package ref'
        required: false
      nr_persistent_context_release_name:
        description: 'nr-persistent-context package version'
        required: false
        default: 'nightly'
      nr_persistent_context_ref:
        description: 'nr-persistent-context package ref'
        required: false
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package.yml@e3e734b910af78371b2c9a1c6856446d17421f50'
    with:
      run_tests: true

  nrLauncherPackage:
    needs: build
    if: |
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
      ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' )
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@5e57b30ac6ed8478406b3b3f2780241d2f4dcd8f'
    with:
      package_name: flowforge-nr-launcher
      publish_package: true
      package_dependencies: |
        @flowforge/nr-project-nodes
        @flowforge/nr-file-nodes
        @flowforge/nr-persistent-context
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}
  
  nrThemePackage:
    needs: build
    if: |
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
      ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' )
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@5e57b30ac6ed8478406b3b3f2780241d2f4dcd8f'
    with:
      package_name: flowforge-nr-theme
      publish_package: true
      working_directory: ./lib/theme
      disable_ignore_scripts_on_publish: true
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}

  dispatch:
    name: Dispatch localfs package build pipeline
    runs-on: ubuntu-latest
    needs: [nrLauncherPackage, nrThemePackage]
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}

      - name: Trigger localfs package build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          repo: flowforge/flowforge-driver-localfs
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"nr_launcher_ref": "${{ github.ref }}", "nr_launcher_release_name": "${{ needs.nrLauncherPackage.outputs.release_name }}"}'
